# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: devops

stages:
  - stage: terraformvalidate
    jobs:
      - job: TerraformValidateJob
        continueOnError: false
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish Artifacts
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/01-terraform-mainfests-aks'
              artifact: 'terraform-manifests-out'
              publishLocation: 'pipeline'
          
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'
          - task: TerraformCLI@2
            inputs:
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/01-terraform-mainfests-aks'
              backendType: 'azurerm'
              backendServiceArm: 'terraform-azure-aks-svc-conn'
              backendAzureRmResourceGroupName: 'terraform-storage-rg1'
              backendAzureRmStorageAccountName: 'terraformdevon1006'
              backendAzureRmContainerName: 'terraform'
              backendAzureRmKey: 'terraform.tfstate'
              allowTelemetryCollection: false'
          
          - task: TerraformCLI@2
            inputs:
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/01-terraform-mainfests-aks'
              allowTelemetryCollection: false
          
          